### ISSUE TITLE
开源数据集

### ISSUE THREAD

**Issue by whz-snn** [Event-AHU/HARDVS#1]
请问有没有可以wget的链接直接获取数据集，220G百度网盘太慢了

**Comment by wangxiao5791509** [comment]
@whz-snn  目前还没有。可以考虑开个会员。

**Comment by linyuming0722** [comment]
按照README里面的指示配置环境之后出现了‘cannot import name 'Config' from 'mmcv'这个错误，一开始我认为是mmcv版本的问题，但是换了很多版本尝试过了，mmcv2.0以上的版本都是报‘cannot import name 'Config' from 'mmcv’这个错误，1.4-1.7版本的会报‘cannot import name 'CUDA_HOME' from 'mmcv.utils'’错误，请问要怎么解决呢？

**Comment by wangxiao5791509** [comment]
@WuZongzhen

**Comment by QiWang233** [comment]
![image](https://github.com/Event-AHU/HARDVS/assets/59739521/e1c8a28d-3338-4798-aac2-b94bd409baa8)

Hi, Wang:

1. When I try to recurrent, I found these missing parameters in the above picture.I wonder if you can tell me the meaning of these parameters in detail. 

2. Also, I got three list files ('test_label' 'train_label' and 'val_label') in Baidu Netdisk which I don't know how to use it correctly.

Looking forward to your reply.

Best wishes
Qi

**Comment by WuZongzhen** [comment]
> 按照README里面的指示配置环境之后出现了‘cannot import name 'Config' from 'mmcv'这个错误，一开始我认为是mmcv版本的问题，但是换了很多版本尝试过了，mmcv2.0以上的版本都是报‘cannot import name 'Config' from 'mmcv’这个错误，1.4-1.7版本的会报‘cannot import name 'CUDA_HOME' from 'mmcv.utils'’错误，请问要怎么解决呢？

You can try running the code in the following version:
cuda       9.1 ,
torch        1.8.1+cu111,
mmcv-full          1.7.0

**Comment by QiWang233** [comment]
已收到邮件。

**Comment by WuZongzhen** [comment]
> 1. When I try to recurrent, I found these missing parameters in the above picture.I wonder if you can tell me the meaning of these parameters in detail.
> 2. Also, I got three list files ('test_label' 'train_label' and 'val_label') in Baidu Netdisk which I don't know how to use it correctly.


This section is the dataset path, you can check the updated files.
