### ISSUE TITLE
环境问题 ‘cannot import name 'Config' from 'mmcv'

### ISSUE THREAD

**Issue by Asaasx** [Event-AHU/HARDVS#2]
严格按照readme配置环境会报错：‘cannot import name 'Config' from 'mmcv'，查了一下发现是mmcv2.0.0以后就没有Config了，
换成<2.0.0以后发现mmaction有很多报错，按readme安装很多mmaction中的类和函数都没有，是否能提供更加完整和详细的环境

**Comment by WuZongzhen** [comment]
You can try running the code in the following version:
cuda       9.1,
torch        1.8.1+cu111,
mmcv-full          1.7.0

**Comment by zqqqyu** [comment]
感谢您的回复，我重新安装了mmcv=1.7.0,但这似乎与mmaction2不兼容，会出现以下错误：
mmaction2 1.2.0 requires mmcv<2.2.0,>=2.0.0rc4, which is not installed.
AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

**Comment by WuZongzhen** [comment]
![图片1](https://github.com/Event-AHU/HARDVS/assets/103302166/15fb7e7c-9661-4876-bc3b-c41c570e0472)
我的安装的是：   mmcv-full  1.7.0，如图版本。

**Comment by zqqqyu** [comment]
您好，所提交的代码中的[mmaction](https://github.com/Event-AHU/HARDVS/tree/main/mmaction)似乎缺少一些必要的文件, 比如utils、models，用mmaction2中的包补充后还是无法正常运行，是否能够提供更加完整的代码

**Comment by WuZongzhen** [comment]
请查看更新后的代码，当前提交代码可以运行。

**Comment by MrGoldminer** [comment]
> 感谢您的回复，我重新安装了mmcv=1.7.0,但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0,>=2.0.0rc4, which is not installed. AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

所以这个解决了吗？

**Comment by MrGoldminer** [comment]
> 请查看更新后的代码，当前提交代码可以运行。

可以给个链接吗？

**Comment by ssp-seven** [comment]
> > 感谢您的回复，我重新安装了mmcv=1.7.0,但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0,>=2.0.0rc4, which is not installed. AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
> 
> 所以这个解决了吗？

Hello, have you resolved the issue?

**Comment by zqqqyu** [comment]
> > > 感谢您的回复，我重新安装了mmcv=1.7.0,但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0,>=2.0.0rc4, which is not installed. AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
> > 
> > 
> > 所以这个解决了吗？
> 
> Hello, have you resolved the issue?

I've solved the problem, it required the specified version of the package to be installed.

**Comment by ssp-seven** [comment]
> > > > 感谢您的回复，我重新安装了mmcv=1.7.0，但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0，>=2.0.0rc4，但未安装。AssertionError：使用 MMCV==1.7.0 但不兼容。请安装 mmcv>=2.0.0rc4、<2.2.0。
> > > 
> > > 
> > > 所以这个解决了吗？
> > 
> > 
> > 您好，您解决了问题吗？
> 
> 我已经解决了这个问题，它需要安装指定版本的软件包。

Thank you for your answer! May I ask if you know what is the difference in the role of rawframes.zip and MINIHARDVSEVENT_files.zip in the provided data in the project?

**Comment by zqqqyu** [comment]
> > > > > 感谢您的回复，我重新安装了mmcv=1.7.0，但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0，>=2.0.0rc4，但未安装。AssertionError：使用 MMCV==1.7.0 但不兼容。请安装 mmcv>=2.0.0rc4、<2.2.0。
> > > > 
> > > > 
> > > > 所以这个解决了吗？
> > > 
> > > 
> > > 您好，您解决了问题吗？
> > 
> > 
> > 我已经解决了这个问题，它需要安装指定版本的软件包。
> 
> Thank you for your answer! May I ask if you know what is the difference in the role of rawframes.zip and MINIHARDVSEVENT_files.zip in the provided data in the project?

The rawframes.zip contains .png files, and the MINIHARDVSEVENT_files.zip contains .npz files.

**Comment by ssp-seven** [comment]
> > > > > > 感谢您的回复，我重新安装了mmcv=1.7.0，但这似乎与mmaction2不兼容，会出现以下错误： mmaction2 1.2.0 requires mmcv<2.2.0，>=2.0.0rc4，但未安装。AssertionError：使用 MMCV==1.7.0 但不兼容。请安装 mmcv>=2.0.0rc4、<2.2.0。
> > > > > 
> > > > > 
> > > > > 所以这个解决了吗？
> > > > 
> > > > 
> > > > 您好，您解决了问题吗？
> > > 
> > > 
> > > 我已经解决了这个问题，它需要安装指定版本的软件包。
> > 
> > 
> > Thank you for your answer! May I ask if you know what is the difference in the role of rawframes.zip and MINIHARDVSEVENT_files.zip in the provided data in the project?
> 
> rawframes.zip包含 .png 个文件，MINIHARDVSEVENT_files.zip包含 .npz 文件。

Thank you very much！

**Comment by ssp-seven** [comment]
> MINIHARDVSEVENT_files.zip

Sorry to bother you again. Is training using a dataset from rawframes.zip? Alternatively, both rawframes.zip and MINIHARDVSEVENT_files.zip datasets can be run. What is the difference in the actual training effect? Is MINIHARDVSEVENT_files.zip the original event stream captured by the event camera? Is rawframes.zip the event image obtained through further processing? Is this understanding correct? Thank you very much for your answer!
