### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Asaasx** [Event-AHU/HARDVS#3]
网盘中提供了list，MINIHARDVS_EVENT_files, rawframes,
数据集是用网盘中的rawframes吗，是否需要进一步的处理，直接用网盘的数据集无法正常运行：
FileNotFoundError: [Errno 2] No such file or directory: '.../wzz_300HarDvs/rawframes/action_130/dvSave-2021_09_28_19_29_23/00000000.png', 网盘中的数据集多了dvSave-2021_09_28_19_29_23_dvs这个路径，修改后：
FileNotFoundError: [Errno 2] No such file or directory: '.../wzz_300HarDvs/rawframes/action_130/dvSave-2021_09_28_19_29_23/00000001.png'，提供的数据集为'00000000.png', '00000005.png', '00000010.png'，修改后又有新的错误：
Assertion `t &gt;= 0 &amp;&amp; t &lt; n_classes` failed.
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
是否能够提供数据集的使用说明

**Comment by WuZongzhen** [comment]
貌似是预测类别与标签数量对应问题，请查看使用更新的代码。
