### ISSUE TITLE
result error

### ISSUE THREAD

**Issue by junkangfang** [Event-AHU/HARDVS#6]
{"mode": "train", "epoch": 50, "iter": 2300, "lr": 1e-05, "memory": 5808, "data_time": 1.81207, "top1_acc": 0.2528, "top5_acc": 0.2696, "loss_cls": 4.24143, "loss": 4.24143, "grad_norm": 1.43265, "time": 2.03297}
{"mode": "train", "epoch": 50, "iter": 2400, "lr": 1e-05, "memory": 5808, "data_time": 1.4463, "top1_acc": 0.254, "top5_acc": 0.2668, "loss_cls": 4.24071, "loss": 4.24071, "grad_norm": 1.53618, "time": 1.66408}
{"mode": "train", "epoch": 50, "iter": 2500, "lr": 1e-05, "memory": 5808, "data_time": 1.61799, "top1_acc": 0.2372, "top5_acc": 0.258, "loss_cls": 4.32051, "loss": 4.32051, "grad_norm": 1.59426, "time": 1.83132}
{"mode": "val", "epoch": 50, "iter": 430, "lr": 1e-05, "top1_acc": 0.67431, "top5_acc": 0.77064, "mean_class_accuracy": 0.71983}

I have successfully run your code, but the accuracy is very low. Is this correct?

**Comment by junkangfang** [comment]
"And when I reached the 17th epoch, the code automatically stopped, and I'm not sure why."

**Comment by junkangfang** [comment]
![Uploading }DL1[8OEOUC[IE6~HUJFZ[4.png…]()

**Comment by junkangfang** [comment]
![}DL1 8OEOUC IE6~HUJFZ 4](https://github.com/Event-AHU/HARDVS/assets/136902319/257b2b3a-612c-4ddb-a084-a1671098f7c1)
![Uploading }DL1[8OEOUC[IE6~HUJFZ[4.png…]()

**Comment by ssp789** [comment]
Hello, have you resolved this issue?
