### ISSUE TITLE
Access the illumination type of each sample in HARDVS

### ISSUE THREAD

**Issue by MrFisher97** [Event-AHU/HARDVS#7]
Hi,

I am interested in your research on event cameras. In particular, I noticed that the HARDVS dataset was captured in multiple lighting scenarios. However, I was not able to get the illumination information for the HARDVS dataset from the provided GitHub repository, e.g., what type of illumination (strong or low light) the samples were captured under.

I would greatly appreciate it if you could provide access to the illumination type of each sample  or direct me to the appropriate location where I can find it.

Thank you for your time and consideration.

Best regards,
fisher.

**Comment by wangxiao5791509** [comment]
@wanzengy  Hi, sorry to inform you that the illumination type for each video is not recorded when collecting this dataset. Therefore, we can't provide such as file. T_T

**Comment by MrFisher97** [comment]
Ok, I understand it and apperaciate your sharing again.
